### ISSUE TITLE
Show only the first upstream repo in which a commit is present

### ISSUE THREAD

**Issue by dtardon** [redhat-plumbers-in-action/advanced-commit-linter#62]
### Type of issue

Feature Request

### Description

Currently, if multiple upstream repos's are specified, the linter looks for a commit in all of them, with output like:

#### The following commits meet all requirements

| commit | upstream |
|---|---|
| https://github.com/redhat-plumbers/systemd-rhel8/commit/36a944a186f2cbc9d9301fe27d1357ef26ec32ad - _logind: simplify code_ | https://github.com/systemd/systemd/commit/e5c09aad375551b9db499703ab7eb123d408ba16</br>https://github.com/systemd/systemd-stable/commit/e5c09aad375551b9db499703ab7eb123d408ba16 |

I don't see much value in doing that in general and it's completely pointless in this particular case, as every commit from `systemd/systemd` will be present in `systemd/systemd-stable` eventually.

### Describe the solution you'd like

List just the first upstream repo that contains the commit. Example:

#### The following commits meet all requirements

| commit | upstream |
|---|---|
| https://github.com/redhat-plumbers/systemd-rhel8/commit/36a944a186f2cbc9d9301fe27d1357ef26ec32ad - _logind: simplify code_ | https://github.com/systemd/systemd/commit/e5c09aad375551b9db499703ab7eb123d408ba16 |

**Comment by jamacku** [comment]
I thought it might be a good indicator if the commit is also present in Fedora. But you are right that showing both links isn't useful most of the time since almost always commit is already in stable repo anyway.

One of the solutions could be to drop `systemd/systemd-stable` from `.github/.advanced-commit-linter.yml`. Or I can show only one link (essentially hardcoding it to actions code) or hide it behind a switch.

@dtardon What would you prefer?

**Comment by dtardon** [comment]
> I thought it might be a good indicator if the commit is also present in Fedora.

Just checking a presence of a commit is not enough. One would have to check if the commit is on some `systemd-stable`'s release branch. But that doesn't work for cherry-picked commits, because their SHA is different, hence it's not very reliable indicator.

> One of the solutions could be to drop `systemd/systemd-stable` from `.github/.advanced-commit-linter.yml`.

Yeah, that sounds good to me.

**Comment by jamacku** [comment]
> > One of the solutions could be to drop `systemd/systemd-stable` from `.github/.advanced-commit-linter.yml`.
> 
> Yeah, that sounds good to me.

Ok, I will submit PRs. Thanks for reporting this issue.

**Comment by jamacku** [comment]
I have created PRs. I will close this issue. Feel free to reopen it if needed.
